### ISSUE TITLE
CreateTopic example fails

### ISSUE THREAD

**Issue by ajhunyady** [infinyon/fluvio-client-node#34]
$ ts-node ./examples/createTopic.ts
requiring platform specific module
/Users/aj/projects/github/fluvio-client-node/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1055:16)
    at Module._compile (internal/modules/cjs/loader.js:1103:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/aj/projects/github/fluvio-client-node/examples/createTopic.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Module.m._compile (/Users/aj/.nvm/versions/node/v13.5.0/lib/node_modules/ts-node/src/index.ts:1043:23)

**Comment by ajhunyady** [comment]
fixed.
